# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ecd2234ae59fb296887f818441de52d2ff7fdc934956cb990e5be814f2c650f7a6b9d9d3d6a03d2965dc730c43f211ea2fc1d6e448bcf6963e4591581fa6d73

test:
  secret_key_base: fec31c6cbfac728e277703220b3598ce3ec85b9d8a8798297ef86dfc28589c1517cec77c0cc74748e4e4b5fe05dc42071e4f77a60667498addfef21f4a393578

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
